name: ICSCalendarSyncGUI
options:
  bundleIdPrefix: com.ics-calendar-sync
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

packages:
  SQLite:
    url: https://github.com/stephencelis/SQLite.swift.git
    from: "0.15.3"

targets:
  ICS Calendar Sync:
    type: application
    platform: macOS
    sources:
      - path: Sources/ICSCalendarSyncGUI
        type: group
    resources:
      - path: Resources/Assets.xcassets
    postCompileScripts:
      - name: "Embed CLI Binary"
        script: |
          # Copy CLI binary into app bundle Resources for independent operation
          CLI_SOURCE="${SRCROOT}/.build/release/ics-calendar-sync"
          CLI_DEST="${BUILT_PRODUCTS_DIR}/${CONTENTS_FOLDER_PATH}/Resources/ics-calendar-sync"

          if [ -f "$CLI_SOURCE" ]; then
            mkdir -p "${BUILT_PRODUCTS_DIR}/${CONTENTS_FOLDER_PATH}/Resources"
            cp "$CLI_SOURCE" "$CLI_DEST"
            chmod +x "$CLI_DEST"
            echo "Embedded CLI binary from $CLI_SOURCE to $CLI_DEST"
          else
            # Try debug build
            CLI_SOURCE="${SRCROOT}/.build/debug/ics-calendar-sync"
            if [ -f "$CLI_SOURCE" ]; then
              mkdir -p "${BUILT_PRODUCTS_DIR}/${CONTENTS_FOLDER_PATH}/Resources"
              cp "$CLI_SOURCE" "$CLI_DEST"
              chmod +x "$CLI_DEST"
              echo "Embedded CLI binary from $CLI_SOURCE to $CLI_DEST"
            else
              echo "Warning: CLI binary not found. Build CLI first with 'swift build' or 'swift build -c release'"
            fi
          fi
        basedOnDependencyAnalysis: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ics-calendar-sync.gui
        PRODUCT_NAME: ICS Calendar Sync
        MARKETING_VERSION: "2.1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Resources/ICSCalendarSyncGUI.entitlements
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "5.0"
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: YES
        SWIFT_ENABLE_EXPLICIT_MODULES: NO
    dependencies:
      - package: SQLite
        product: SQLite
    info:
      path: Resources/Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIconName: AppIcon
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSApplicationCategoryType: public.app-category.productivity
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        LSUIElement: true
        NSCalendarsUsageDescription: ICS Calendar Sync needs access to your calendars to sync events from ICS feeds.
        NSHighResolutionCapable: true
        NSPrincipalClass: NSApplication
    entitlements:
      path: Resources/ICSCalendarSyncGUI.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.personal-information.calendars: true

schemes:
  ICS Calendar Sync:
    build:
      targets:
        ICS Calendar Sync: all
    run:
      config: Debug
    archive:
      config: Release
