name: ICSCalendarSyncGUI
options:
  bundleIdPrefix: com.ics-calendar-sync
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

packages:
  SQLite:
    url: https://github.com/stephencelis/SQLite.swift.git
    from: "0.15.3"

targets:
  ICS Calendar Sync:
    type: application
    platform: macOS
    sources:
      - path: Sources/ICSCalendarSyncGUI
        type: group
    resources:
      - path: Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ics-calendar-sync.gui
        PRODUCT_NAME: ICS Calendar Sync
        MARKETING_VERSION: "2.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Resources/ICSCalendarSyncGUI.entitlements
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "5.0"
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: YES
    dependencies:
      - package: SQLite
        product: SQLite
    info:
      path: Resources/Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIconName: AppIcon
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSApplicationCategoryType: public.app-category.productivity
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        LSUIElement: true
        NSCalendarsUsageDescription: ICS Calendar Sync needs access to your calendars to sync events from ICS feeds.
        NSHighResolutionCapable: true
        NSPrincipalClass: NSApplication
    entitlements:
      path: Resources/ICSCalendarSyncGUI.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.personal-information.calendars: true

schemes:
  ICS Calendar Sync:
    build:
      targets:
        ICS Calendar Sync: all
    run:
      config: Debug
    archive:
      config: Release
